services:
  - type: web
    name: mechanical-engineering-toolkit
    env: node
    plan: free
    buildCommand: npm install && npm run build --prefix client && npm install --prefix server
    startCommand: npm start --prefix server