services:
  - type: web
    name: mechanical-engineering-toolkit
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: cd server && npm start